spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${damn.datasource.driver-class-name}
    url: jdbc:mysql://${damn.datasource.host}:${damn.datasource.port}/${damn.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: ${damn.datasource.username}
    password: ${damn.datasource.password}
    
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bydbishe.entity
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  level:
    com:
      bydbishe:
        mapper: debug
        service: info
        controller: info
        
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql